name: caviar
description: "This is a multi vendor food ordering mobile app"

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  country_picker: ^2.0.25
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  glass: ^2.0.0+1
  google_fonts: ^6.2.1
  #google_maps_flutter: ^2.6.1
  http: ^1.2.1
  iconsax: ^0.0.8
  lottie: ^3.1.0
  otp_text_field: ^1.1.3
  shimmer: ^3.0.0
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:
  
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/products/
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  