// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYizEOrIVKhYjBGMZYH-ydaVKZq52fTvQ',
    appId: '1:646447004882:web:1b04ae5257ce82981f810b',
    messagingSenderId: '646447004882',
    projectId: 'caviar-70085',
    authDomain: 'caviar-70085.firebaseapp.com',
    storageBucket: 'caviar-70085.appspot.com',
    measurementId: 'G-C7X6RM4HSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpgSFTzLib7eQGeW3GUsUa3GPdBwTlxls',
    appId: '1:646447004882:android:f2043e1062b8d4191f810b',
    messagingSenderId: '646447004882',
    projectId: 'caviar-70085',
    storageBucket: 'caviar-70085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB27Mjg1lrCQm3ZQPwXqwpXbgWVF7CA7xE',
    appId: '1:646447004882:ios:a46884c0d7f6db891f810b',
    messagingSenderId: '646447004882',
    projectId: 'caviar-70085',
    storageBucket: 'caviar-70085.appspot.com',
    iosBundleId: 'com.example.caviar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB27Mjg1lrCQm3ZQPwXqwpXbgWVF7CA7xE',
    appId: '1:646447004882:ios:654c219234f96bb41f810b',
    messagingSenderId: '646447004882',
    projectId: 'caviar-70085',
    storageBucket: 'caviar-70085.appspot.com',
    iosBundleId: 'com.example.caviar.RunnerTests',
  );
}
